spring:
  application:
    name: backend

  datasource:
      url: jdbc:mysql://thomas.proxy.rlwy.net:30933/railway?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: pvQOwOFwsaAFNVPQEGdANfudlcoZYhPR
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  address: 0.0.0.0
  port: 8080